server:
  port: 8170
spring:
  profiles:
    active: dev
  application:
    name: service-trade
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
    sentinel:
      transport:
        port: 8081
        dashboard: localhost:8080
      eager: true #取消控制台懒加载，服务启动即可看到sentinel中对当前服务的监控
      filter:
        url-patterns: /** #默认拦截规则为 /*

  datasource:
    username: croot
    password: root
    url: jdbc:mysql://localhost:3306/guli_trade?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    date-format: yyyy-MM-dd
    # time-zone: GMT+8  如果数据库连接serverTimezone=GMT 请加上

  #spring:
  redis:
    host: 192.168.75.130
    port: 6379
    database: 0
    #password: 123456 #默认为空
    lettuce:
      pool:
        max-active: 20  #最大连接数，负值表示没有限制，默认8
        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
        max-idle: 8     #最大空闲连接，默认8
        min-idle: 0     #最小空闲连接，默认0

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #mybatis日志
  mapper-locations: classpath:com/atguigu/guli/service/trade/mapper/xml/*.xml

ribbon:
  ConnectTimeout: 10000 #连接建立的超时时长，默认1秒
  ReadTimeout: 10000 #处理请求的超时时间，默认为1秒

feign:
  sentinel:
    enabled: true

weixin:
  pay:
    #关联的公众号appid
    appId: wxf913bfa3a2c7eeeb
    #商户号
    partner: 1543338551
    #商户key
    partnerKey: atguigu3b0kn9g5vAtGuifHQH7X8rKCL
    #回调地址:必须是公网能访问的地址
    notifyUrl: http://guli-cr.cn.utools.club/api/trade/weixin-pay/notify