server:
  port: 8160
#  tomcat:
#    max-threads: 2  #设置tomcat最大并发数量：默认200一般不修改
spring:
#  datasource:
#    username: croot
#    password: root
#    url: jdbc:mysql://localhost:3306/guli_ucenter?serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#  jackson:
#    date-format: yyyy-MM-dd
    # time-zone: GMT+8  如果数据库连接serverTimezone=GMT 请加上
  profiles:
    active: dev
  application:
    name: service-ucenter
  #Nacos 注册地址
#  cloud:
#    nacos:
#      discovery:
#        server-addr: localhost:8848
#    sentinel:
#      filter:
#        url-patterns: /**
#      eager: true #懒加载：项目启动时如果为true会自动将自己注册到sentinel控制台
#      transport:
#        port: 8081 # 本项目和sentinel控制台数据交流的端口号
#        dashboard: localhost:8080  # sentienl控制面板的地址
#  redis:
#    host: 192.168.75.130
#    port: 6379
    #password: 123456 #默认为空
#    lettuce:
#      pool:
#        max-active: 20  #最大连接数，负值表示没有限制，默认8
#        max-wait: -1    #最大阻塞等待时间，负值表示没限制，默认-1
#        max-idle: 8     #最大空闲连接，默认8
#        min-idle: 0     #最小空闲连接，默认0
#  session: #指定分布式session使用redis缓存
#    store-type: redis
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#  mapper-locations: classpath:com/atguigu/guli/service/ucenter/mapper/xml/*.xml
    #日志配置
#mybatis-plus配置
#日志级别 error warning debug info
#logging:
#  level
#    #root: error
#logging:
#  level:
    #com.atguigu.guli.service.edu.feign.OssFileService: debug #以什么级别监控哪个接口

#设置Feign客户端超时时间（openfeign默认支持ribbon）
#ribbon:
#  MaxAutoRetries: 0 # 同一实例最大重试次数，不包括首次调用，默认0
#  MaxAutoRetriesNextServer: 1 # 重试其他实例的最大重试次数，不包括首次所选的server，默认1
#  ConnectTimeout: 5000 #指的是建立连接所用的时间，适用于网络状况正常的情况下，两端连接所用的时间
#  ReadTimeout: 5000 #指的是建立连接后从服务器读取到可用资源所用的时间
#service-oss: # 调用的提供者的名称:配置负载均衡策略
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule


#开启Feign对Sentinel的支持
#feign:
#  sentinel:
#    enabled: true

#wx:
#  open:
#    # 微信开放平台 appid
#    appId: wxed9954c01bb89b47
#    # 微信开放平台 appsecret
#    appSecret: a7482517235173ddb4083788de60b90e
#    # 微信开放平台 重定向url（guli.shop需要在微信开放平台配置）
#    redirectUri: http://guli.shop/api/ucenter/wx/callback8160